### ISSUE TITLE
"Please try again soon" is the text massage reveals opening the app page

### ISSUE THREAD

**Issue by kyrmich** [watson-developer-cloud/questions-with-classifier-ega#62] opened 2016-02-11 19:25 UTC
I try to configure the question-with-classfier-ega following the steps described on https://github.com/watson-developer-cloud/questions-with-classifier-ega but something seems does not work correctly.
 
Do you have any idea why i get the following message when i open the corresponding page of my app.

"Please try again soon".  Look the attached pictures

<img width="1280" alt="screen shot 2016-02-10 at 21 50 45" src="https://cloud.githubusercontent.com/assets/17172219/12987660/bacb00ac-d105-11e5-82e0-25d21f403f4f.png">
<img width="1280" alt="screen shot 2016-02-11 at 21 22 07" src="https://cloud.githubusercontent.com/assets/17172219/12987670/cc7cd9a6-d105-11e5-8c44-61977404a63d.png">

Thanks in advance

**Comment by tdalbo92** [comment] 2016-02-11 19:30
Could you look at the logs in bluemix and paste them here?  

Additionally, make sure your classifier has been trained and you've uploaded your answer store.  Since the classifier has been bound properly I think the problem you're running into is related to the answer store.

**Comment by kyrmich** [comment] 2016-02-11 19:36
hmmm....many errors!!!

2016-02-11T20:55:41.298+0200[RTR/1]OUTmypersonalagent.mybluemix.net - [11/02/2016:18:55:41 +0000] "GET /css/style.css HTTP/1.1" 304 0 0 "http://mypersonalagent.mybluemix.net/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_2) AppleWebKit/601.3.9 (KHTML, like Gecko) Version/9.0.2 Safari/601.3.9" 192.155.237.115:41643 x_forwarded_for:"31.153.78.169" x_forwarded_proto:"http" vcap_request_id:1bf5b203-5bed-4d04-7ade-35324c09ade3 response_time:0.004485768 app_id:1c43f3a7-e15f-4d7b-b74c-e9bdebef42ae x_global_transaction_id:"158655953"
2016-02-11T20:55:41.582+0200[RTR/0]OUTmypersonalagent.mybluemix.net - [11/02/2016:18:55:41 +0000] "GET /js/bundle.js HTTP/1.1" 304 0 0 "http://mypersonalagent.mybluemix.net/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_2) AppleWebKit/601.3.9 (KHTML, like Gecko) Version/9.0.2 Safari/601.3.9" 192.155.237.114:34779 x_forwarded_for:"31.153.78.169" x_forwarded_proto:"http" vcap_request_id:634cd1f6-905d-4ac5-519d-e9314c7737c8 response_time:0.007482348 app_id:1c43f3a7-e15f-4d7b-b74c-e9bdebef42ae x_global_transaction_id:"165209263"
2016-02-11T20:55:41.819+0200[RTR/0]OUTmypersonalagent.mybluemix.net - [11/02/2016:18:55:41 +0000] "GET /strings/en.json HTTP/1.1" 304 0 0 "http://mypersonalagent.mybluemix.net/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_2) AppleWebKit/601.3.9 (KHTML, like Gecko) Version/9.0.2 Safari/601.3.9" 192.155.237.114:34786 x_forwarded_for:"31.153.78.169" x_forwarded_proto:"http" vcap_request_id:ee34bc9c-d9da-4d0b-58e3-574681ed0d6b response_time:0.004382575 app_id:1c43f3a7-e15f-4d7b-b74c-e9bdebef42ae x_global_transaction_id:"163082695"
2016-02-11T20:55:42.042+0200[RTR/0]OUTmypersonalagent.mybluemix.net - [11/02/2016:18:55:42 +0000] "GET /images/Default.svg HTTP/1.1" 304 0 0 "http://mypersonalagent.mybluemix.net/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_2) AppleWebKit/601.3.9 (KHTML, like Gecko) Version/9.0.2 Safari/601.3.9" 192.155.237.114:34786 x_forwarded_for:"31.153.78.169" x_forwarded_proto:"http" vcap_request_id:ae78f08c-6e85-4724-6a6d-7d01997622f1 response_time:0.004712602 app_id:1c43f3a7-e15f-4d7b-b74c-e9bdebef42ae x_global_transaction_id:"158658305"
2016-02-11T20:55:42.043+0200[RTR/0]OUTmypersonalagent.mybluemix.net - [11/02/2016:18:55:42 +0000] "GET /images/close-icon.svg HTTP/1.1" 304 0 0 "http://mypersonalagent.mybluemix.net/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_2) AppleWebKit/601.3.9 (KHTML, like Gecko) Version/9.0.2 Safari/601.3.9" 192.155.237.114:34789 x_forwarded_for:"31.153.78.169" x_forwarded_proto:"http" vcap_request_id:6655fe8f-7d0f-4ece-44ba-7402deee8c14 response_time:0.003517841 app_id:1c43f3a7-e15f-4d7b-b74c-e9bdebef42ae x_global_transaction_id:"158658193"
2016-02-11T20:55:42.050+0200[RTR/0]OUTmypersonalagent.mybluemix.net - [11/02/2016:18:55:42 +0000] "GET /images/Badge_88.svg HTTP/1.1" 304 0 0 "http://mypersonalagent.mybluemix.net/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_2) AppleWebKit/601.3.9 (KHTML, like Gecko) Version/9.0.2 Safari/601.3.9" 192.155.237.116:47358 x_forwarded_for:"31.153.78.169" x_forwarded_proto:"http" vcap_request_id:41ec5f8e-dbfa-4e68-6951-384cbf9be581 response_time:0.002864913 app_id:1c43f3a7-e15f-4d7b-b74c-e9bdebef42ae x_global_transaction_id:"160428337"
2016-02-11T20:55:42.241+0200[RTR/1]OUTmypersonalagent.mybluemix.net - [11/02/2016:18:55:42 +0000] "GET /images/Wrong_88.svg HTTP/1.1" 304 0 0 "http://mypersonalagent.mybluemix.net/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_2) AppleWebKit/601.3.9 (KHTML, like Gecko) Version/9.0.2 Safari/601.3.9" 192.155.237.117:40002 x_forwarded_for:"31.153.78.169" x_forwarded_proto:"http" vcap_request_id:88336fd9-3d8c-4066-7a5b-92626116cd71 response_time:0.00552925 app_id:1c43f3a7-e15f-4d7b-b74c-e9bdebef42ae x_global_transaction_id:"156324527"
2016-02-11T20:55:42.242+0200[RTR/1]OUTmypersonalagent.mybluemix.net - [11/02/2016:18:55:42 +0000] "GET /images/loading-indicator.svg HTTP/1.1" 304 0 0 "http://mypersonalagent.mybluemix.net/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_2) AppleWebKit/601.3.9 (KHTML, like Gecko) Version/9.0.2 Safari/601.3.9" 192.155.237.115:41668 x_forwarded_for:"31.153.78.169" x_forwarded_proto:"http" vcap_request_id:3d89a24b-0429-478a-7516-486687284fe6 response_time:0.004101056 app_id:1c43f3a7-e15f-4d7b-b74c-e9bdebef42ae x_global_transaction_id:"163082807"
2016-02-11T20:55:42.267+0200[RTR/0]OUTmypersonalagent.mybluemix.net - [11/02/2016:18:55:42 +0000] "GET /images/Correct_88.svg HTTP/1.1" 304 0 0 "http://mypersonalagent.mybluemix.net/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_2) AppleWebKit/601.3.9 (KHTML, like Gecko) Version/9.0.2 Safari/601.3.9" 192.155.237.114:47627 x_forwarded_for:"31.153.78.169" x_forwarded_proto:"http" vcap_request_id:b4d5c7de-0204-4395-4099-92cc78cb0f0d response_time:0.006396882 app_id:1c43f3a7-e15f-4d7b-b74c-e9bdebef42ae x_global_transaction_id:"165209551"
2016-02-11T20:55:42.307+0200[App/0]OUTCall: SELECT CLASS, TEXT, TYPE, CANONICAL_QUESTION FROM ANSWERS
2016-02-11T20:55:42.307+0200[App/0]OUTInternal Exception: com.ibm.db2.jcc.am.SqlSyntaxErrorException: "USER14448.ANSWERS" is an undefined name.. SQLCODE=-204, SQLSTATE=42704, DRIVER=4.17.29
2016-02-11T20:55:42.307+0200[App/0]OUTError Code: -204
2016-02-11T20:55:42.307+0200[App/0]OUT[WARNING ] CWWJP9991W: Exception [EclipseLink-4002] (Eclipse Persistence Services - 2.6.1.WAS-v20160106-a06c2b3): org.eclipse.persistence.exceptions.DatabaseException
2016-02-11T20:55:42.307+0200[App/0]OUTQuery: ReadAllQuery(name="Answers.getAllAnswers" referenceClass=AnswerEntity sql="SELECT CLASS, TEXT, TYPE, CANONICAL_QUESTION FROM ANSWERS")
2016-02-11T20:55:42.311+0200[App/0]ERR at [internal classes]
2016-02-11T20:55:42.311+0200[App/0]ERR at [internal classes]
2016-02-11T20:55:42.311+0200[App/0]ERR at com.ibm.watson.app.common.util.rest.CORSFilter.doFilter(CORSFilter.java:38)
2016-02-11T20:55:42.311+0200[App/0]ERR at com.ibm.ws.jaxrs20.server.LibertyJaxRsServerFactoryBean.createSingletonInstance(LibertyJaxRsServerFactoryBean.java:220)
2016-02-11T20:55:42.311+0200[App/0]ERR[ERROR ] SRVE0271E: Uncaught init() exception created by servlet [Classifier JAX-RS Servlet] in application [myapp]: javax.servlet.ServletException: Resource class com.ibm.watson.app.qaclassifier.ClassifierApplicationImpl can not be instantiated due to InvocationTargetException
2016-02-11T20:55:42.311+0200[App/0]ERR at com.ibm.ws.webcontainer.filter.FilterInstanceWrapper.doFilter(FilterInstanceWrapper.java:207)
2016-02-11T20:55:42.320+0200[RTR/0]OUTmypersonalagent.mybluemix.net - [11/02/2016:18:55:42 +0000] "POST /api/v1/conversation/ HTTP/1.1" 500 0 2034 "http://mypersonalagent.mybluemix.net/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_2) AppleWebKit/601.3.9 (KHTML, like Gecko) Version/9.0.2 Safari/601.3.9" 192.155.237.118:10304 x_forwarded_for:"31.153.78.169" x_forwarded_proto:"http" vcap_request_id:65d4a6a3-2ea4-43db-430e-180fa13e85d5 response_time:0.042118735 app_id:1c43f3a7-e15f-4d7b-b74c-e9bdebef42ae x_global_transaction_id:"148904991"
2016-02-11T21:33:25.766+0200[App/0]OUTError Code: -204
2016-02-11T21:33:25.766+0200[App/0]OUTInternal Exception: com.ibm.db2.jcc.am.SqlSyntaxErrorException: "USER14448.ANSWERS" is an undefined name.. SQLCODE=-204, SQLSTATE=42704, DRIVER=4.17.29
2016-02-11T21:33:25.766+0200[App/0]OUTCall: SELECT CLASS, TEXT, TYPE, CANONICAL_QUESTION FROM ANSWERS
2016-02-11T21:33:25.766+0200[App/0]OUTQuery: ReadAllQuery(name="Answers.getAllAnswers" referenceClass=AnswerEntity sql="SELECT CLASS, TEXT, TYPE, CANONICAL_QUESTION FROM ANSWERS")
2016-02-11T21:33:25.766+0200[App/0]OUT[WARNING ] CWWJP9991W: Exception [EclipseLink-4002] (Eclipse Persistence Services - 2.6.1.WAS-v20160106-a06c2b3): org.eclipse.persistence.exceptions.DatabaseException
2016-02-11T21:33:25.769+0200[App/0]ERR at [internal classes]
2016-02-11T21:33:25.769+0200[App/0]ERR at [internal classes]
2016-02-11T21:33:25.769+0200[App/0]ERR at com.ibm.ws.jaxrs20.server.LibertyJaxRsServerFactoryBean.createSingletonInstance(LibertyJaxRsServerFactoryBean.java:220)
2016-02-11T21:33:25.769+0200[App/0]ERR at com.ibm.ws.webcontainer.filter.FilterInstanceWrapper.doFilter(FilterInstanceWrapper.java:207)
2016-02-11T21:33:25.769+0200[App/0]ERR[ERROR ] SRVE0271E: Uncaught init() exception created by servlet [Classifier JAX-RS Servlet] in application [myapp]: javax.servlet.ServletException: Resource class com.ibm.watson.app.qaclassifier.ClassifierApplicationImpl can not be instantiated due to InvocationTargetException
2016-02-11T21:33:25.769+0200[App/0]ERR at com.ibm.watson.app.common.util.rest.CORSFilter.doFilter(CORSFilter.java:38)
2016-02-11T21:33:25.770+0200[App/0]ERR at com.ibm.ws.webcontainer.webapp.WebApp.handleRequest(WebApp.java:4910)
2016-02-11T21:33:25.770+0200[App/0]ERRCaused by: javax.servlet.ServletException: Resource class com.ibm.watson.app.qaclassifier.ClassifierApplicationImpl can not be instantiated due to InvocationTargetException
2016-02-11T21:33:25.770+0200[App/0]ERR ... 1 more
2016-02-11T21:33:25.770+0200[App/0]ERR at [internal classes]
2016-02-11T21:33:25.770+0200[App/0]ERR at com.ibm.watson.app.common.util.rest.CORSFilter.doFilter(CORSFilter.java:38)
2016-02-11T21:33:25.770+0200[App/0]ERR at com.ibm.ws.webcontainer.filter.FilterInstanceWrapper.doFilter(FilterInstanceWrapper.java:207)
2016-02-11T21:33:25.770+0200[App/0]ERR at com.ibm.ws.jaxrs20.server.LibertyJaxRsServerFactoryBean.createSingletonInstance(LibertyJaxRsServerFactoryBean.java:220)
2016-02-11T21:33:25.770+0200[App/0]ERR at [internal classes]
2016-02-11T21:33:25.770+0200[App/0]ERR[ERROR ] SRVE0315E: An exception occurred: java.lang.Throwable: javax.servlet.ServletException: Resource class com.ibm.watson.app.qaclassifier.ClassifierApplicationImpl can not be instantiated due to InvocationTargetException
2016-02-11T21:35:34.547+0200[App/0]OUTInternal Exception: com.ibm.db2.jcc.am.SqlSyntaxErrorException: "USER14448.ANSWERS" is an undefined name.. SQLCODE=-204, SQLSTATE=42704, DRIVER=4.17.29
2016-02-11T21:35:34.547+0200[App/0]OUT[WARNING ] CWWJP9991W: Exception [EclipseLink-4002] (Eclipse Persistence Services - 2.6.1.WAS-v20160106-a06c2b3): org.eclipse.persistence.exceptions.DatabaseException
2016-02-11T21:35:34.547+0200[App/0]OUTQuery: ReadAllQuery(name="Answers.getAllAnswers" referenceClass=AnswerEntity sql="SELECT CLASS, TEXT, TYPE, CANONICAL_QUESTION FROM ANSWERS")
2016-02-11T21:35:34.547+0200[App/0]OUTCall: SELECT CLASS, TEXT, TYPE, CANONICAL_QUESTION FROM ANSWERS
2016-02-11T21:35:34.549+0200[App/0]ERR at com.ibm.watson.app.common.util.rest.CORSFilter.doFilter(CORSFilter.java:38)
2016-02-11T21:35:34.549+0200[App/0]ERR at [internal classes]
2016-02-11T21:35:34.547+0200[App/0]OUTError Code: -204
2016-02-11T21:35:34.549+0200[App/0]ERR[ERROR ] SRVE0271E: Uncaught init() exception created by servlet [Classifier JAX-RS Servlet] in application [myapp]: javax.servlet.ServletException: Resource class com.ibm.watson.app.qaclassifier.ClassifierApplicationImpl can not be instantiated due to InvocationTargetException
2016-02-11T21:35:34.549+0200[App/0]ERR at com.ibm.ws.jaxrs20.server.LibertyJaxRsServerFactoryBean.createSingletonInstance(LibertyJaxRsServerFactoryBean.java:220)
2016-02-11T21:35:34.549+0200[App/0]ERR at com.ibm.ws.webcontainer.filter.FilterInstanceWrapper.doFilter(FilterInstanceWrapper.java:207)
2016-02-11T21:35:34.549+0200[App/0]ERR at [internal classes]
2016-02-11T21:35:34.552+0200[App/0]ERRCaused by: javax.servlet.ServletException: Resource class com.ibm.watson.app.qaclassifier.ClassifierApplicationImpl can not be instantiated due to InvocationTargetException
2016-02-11T21:35:34.552+0200[App/0]ERR at [internal classes]
2016-02-11T21:35:34.552+0200[App/0]ERR at com.ibm.ws.webcontainer.webapp.WebApp.handleRequest(WebApp.java:4910)
2016-02-11T21:35:34.552+0200[App/0]ERR[ERROR ] SRVE0315E: An exception occurred: java.lang.Throwable: javax.servlet.ServletException: Resource class com.ibm.watson.app.qaclassifier.ClassifierApplicationImpl can not be instantiated due to InvocationTargetException
2016-02-11T21:35:34.552+0200[App/0]ERR at [internal classes]
2016-02-11T21:35:34.552+0200[App/0]ERR at com.ibm.ws.jaxrs20.server.LibertyJaxRsServerFactoryBean.createSingletonInstance(LibertyJaxRsServerFactoryBean.java:220)
2016-02-11T21:35:34.552+0200[App/0]ERR at com.ibm.watson.app.common.util.rest.CORSFilter.doFilter(CORSFilter.java:38)
2016-02-11T21:35:34.552+0200[App/0]ERR ... 1 more
2016-02-11T21:35:34.556+0200[RTR/0]OUTmypersonalagent.mybluemix.net - [11/02/2016:19:35:34 +0000] "POST /api/v1/manage/answer HTTP/1.1" 500 23895 2034 "-" "curl/7.43.0" 192.155.237.114:33358 x_forwarded_for:"31.153.78.169" x_forwarded_proto:"http" vcap_request_id:d675a1ec-0dd4-472e-7b09-4bec4dc7bde4 response_time:0.039354592 app_id:1c43f3a7-e15f-4d7b-b74c-e9bdebef42ae x_global_transaction_id:"166768671"
2016-02-11T21:35:34.552+0200[App/0]ERR at com.ibm.ws.webcontainer.filter.FilterInstanceWrapper.doFilter(FilterInstanceWrapper.java:207)

**Comment by tdalbo92** [comment] 2016-02-11 19:41
I see lots of database problems, which leads me to think it's a problem in the answer store.  

You followed https://github.com/watson-developer-cloud/questions-with-classifier-ega#stage-4-populate-the-answer-store ?

**Comment by kyrmich** [comment] 2016-02-11 19:48
Look what i executed and what i got as output on terminal. Do you think the command has any mistakes?

kyriakos-mbp:questions-with-classifier-ega Kyriakos-MAC$ curl -X POST -H "Content-Type: application/json" -d @questions-with-classifier-ega-war/target/classes/answers.json http://mypersonalagent.mybluemix.net/api/v1/manage/answer

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en-US" lang="en-US">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<style>
body{
    margin:0px;
    padding:0px;
    background-color: #ffffff;
    color:#000;
    font-family:Arial,Verdana,Helvetica,Tahoma,sans-serif;
}
#content {
    font-size: 1em;
    margin-left: 1em;
    margin-right: 1em;
    padding: 1em;
}
h4.basichead {
    font-family:Arial,Verdana,Helvetica,Tahoma,sans-serif;
}
p {
    padding-top: .5em;
}
ul {
    line-height: 1.3em;
}
a:link { 
    color: #c00000 
} 
a:visited { 
    color: #c00000 
}
#page {  
    border: 7px; 
    padding: 7px
}
#box {  
    margin: 0;  
}
#title {
    font-family:Arial,Verdana,Helvetica,Tahoma,sans-serif;
    font-size:24px;
    font-weight: normal;
    color:#274a71;
    padding-bottom:6px;
}
#error {  
    colory: #c00004;  
    margin-bottom: 10px;
}
#code {  
    font-family: monospace;  
    font-size: 8pt;
}
#stack {  
    margin-left: 30px;
}
</style>
</head>
<body>

<div id="content">
  <div id="page">
    <div id="box">

<div id="error"> Exception thrown by application class 'com.ibm.ws.jaxrs20.server.LibertyJaxRsServerFactoryBean.createSingletonInstance:220'
</div>
<div id="code">
javax.servlet.ServletException: Resource class com.ibm.watson.app.qaclassifier.ClassifierApplicationImpl can not be instantiated due to InvocationTargetException<br>
<div id="stack">at com.ibm.ws.jaxrs20.server.LibertyJaxRsServerFactoryBean.createSingletonInstance(LibertyJaxRsServerFactoryBean.java:220)<br>at [internal classes]<br>at com.ibm.watson.app.common.util.rest.CORSFilter.doFilter(CORSFilter.java:38)<br>at com.ibm.ws.webcontainer.filter.FilterInstanceWrapper.doFilter(FilterInstanceWrapper.java:207)<br>at [internal classes]<br>
</div>
</div>    </div>
  </div>
</div>

</body>
</html>

**Comment by tdalbo92** [comment] 2016-02-11 19:53
The answer store definitely seems to be your problem.  Let's be absolutely certain though.

If you can, rebuild your application using `mvn package` and re-push that .ZIP file to this application name.  After that, try running the "Upload Answer Store" command again and we'll see if that works.  It seems like your application isn't running quite right.

**Comment by tdalbo92** [comment] 2016-02-11 19:59
By the way, you can also just copy and paste the entirety of your answers.json file into Swagger and execute the command that way.  Then you don't need to run the curl command. 

http://mypersonalagent.mybluemix.net/api/doc/#!/Manage/createAnswer

**Comment by kyrmich** [comment] 2016-02-11 20:11
look error 401. which username and password does it means?

![untitled](https://cloud.githubusercontent.com/assets/17172219/12989059/40ad2a32-d10c-11e5-8105-38997edfeaa2.png)

**Comment by tdalbo92** [comment] 2016-02-11 20:16
When you deploy, you need to choose a password and set it in the environment variables as described in  [Deploying with Security](https://github.com/watson-developer-cloud/questions-with-classifier-ega#deploying-with-security)

**Comment by kyrmich** [comment] 2016-02-11 20:38
I went one step forward! Actually i have the ability to give questions to classifier but always i get the same answer 

Sorry, I don't understand the question. Please try to rephrase it.
.
Still need help?
I'm sorry. I might not understand your question, or I'm not trained on that topic yet. 

The good news is that the system logs your feedback so that I can be trained to answer more questions about more topics.
Here are some tips:
Ensure you ask a question about the Natural Language Classifier service.
Try to rephrase your question.

**Comment by tdalbo92** [comment] 2016-02-11 21:04
That depends on your training data and your answer data.  If you're just using the default data we provide, then the issue must be with either how the classifier was trained (i.e. it might not have finished training, or was trained incorrectly) or the answer store upload still wasn't successful.

However, it sounds like the answer store upload worked for you, so I'd make sure the classifier was properly trained.

**Comment by kyrmich** [comment] 2016-02-12 16:41
curl -u 3b6844ba-184f-446d-a25f-b6466a9de960:74wBMNgbaKFY -F training_data=@questions.csv -F training_metadata="{\"language\":\"en\",\"name\"\"my_classifier\"}" "https://gateway.watsonplatform.net/natural-language-classifier/api/v1/classifiers"


Running the above command in order to train the classifier i get the following message on terminal

{
  "classifier_id" : "c7fa4ax22-nlc-685",
  "name" : "my_classifier",
  "language" : "en",
  "created" : "2016-02-12T16:34:52.532Z",
  "url" : "https://gateway.watsonplatform.net/natural-language-classifier/api/v1/classifiers/c7fa4ax22-nlc-685",
  "status" : "Training",
  "status_description" : "The classifier instance is in its training phase, not yet ready to accept classify requests"
}


Something does not work i think, as it seems on status description. Do you have any idea what maybe is this?

Thank you.

**Comment by tdalbo92** [comment] 2016-02-12 16:52
That's okay - after 10 minutes or so it'll be fully trained.  Make sure you don't have any other trained classifiers to that instance - our app will only use one, and there's no way to control which one it chooses.

Your answer store is being generated properly as well?  Make sure the answer store labels match exactly to the names of the intents you're using in the classifier.

**Comment by geopapyrus** [comment] 2016-02-23 08:23
I'm having this same error. I posted an issue on a similar question and got no replies. I think you guys need to double check the tutorial. Something is broken on IBM's end.

**Comment by tdalbo92** [comment] 2016-02-23 15:23
@geopapyrus I'll look further into it, and see if I can deploy from scratch.  

I've typically seen this error if one of the required Bluemix services has not been bound properly to the app, but it's a pretty generic error so it could be something else entirely. 

I'll report back with my findings.

**Comment by tdalbo92** [comment] 2016-02-23 20:43
Confirmed that there was a syntax bug in `manifest.yml`, I'll push an update to fix it.  We had to urlencode the colon in order for the "Deploy to Bluemix" button to work, but when we removed that button I forgot to change those char encodings back to the character itself. 

Otherwise I was able to successfully build, deploy, train, and use an application following the instructions.

**Comment by tdalbo92** [comment] 2016-02-24 01:39
@kyrmich @geopapyrus Let me know if this resolves your issues, and I'll close this Issue.

**Closed** 2016-02-25 14:34 UTC
Labels: help wanted

**Comment by geopapyrus** [comment] 2016-02-26 20:53
For everyone having this issue here is how I fixed it:

1) manually set the JBP_CONFIG_LIBERTY environment variable via command line

cf set-env launch-hackaton JBP_CONFIG_LIBERTY "app_archive: {features: [jsp-2.2, jaxrs-1.1, jdbc-4.0, jpa-2.0]}"

or

2)  set it on the BlueMix console 

Once I did it, I got rid of the following warning:

`-----> Warning: Liberty feature set is not specified. Using the default feature set: ["beanValidation-1.1", "cdi-1.2", "ejbLite-3.2", "el-3.0", "jaxrs-2.0", "jdbc-4.1", "jndi-1.0", "jpa-2.1", "jsf-2.2", "jsonp-1.0", "jsp-2.3", "managedBeans-1.0", "servlet-3.1", "websocket-1.1"]. For the best results, explicitly set the features via the JBP_CONFIG_LIBERTY environment variable or deploy the application as a server directory or packaged server with a custom server.xml file`

Which was the root cause of all this.

PS: Even using the latest manifest.xml file I still had the error. So the only solution here is to do any of the 2 approaches above.

**Comment by tdalbo92** [comment] 2016-02-26 20:59
Yes, that would be correct - unless you deleted the app and pushed it with the fixed manifest.yml then the liberty feature set won't be updated.  (remember, you have to rename the service labels in that manifest to the services you've created)

**Comment by geopapyrus** [comment] 2016-02-27 21:19
Btw, this if for a Launch Hackaton project wich I think you guys are sponsoring! Wish us luck!

thanks for the help!
